name: Set Repository Secrets

on:
  workflow_dispatch:

jobs:
  set-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Set Repository Secrets
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          gh secret set VERCEL_TOKEN ''
          gh secret set VERCEL_PROJECT_ID ''
          gh secret set VERCEL_ORG_ID ''
          gh secret set GITHUB_TOKEN ''
          
          if [ -n "" ]; then
            gh secret set SLACK_WEBHOOK ''
          fi