version: '3.8'

services:
  test-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: newsletter_test
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
