services:
  mysql:
    image: mysql:8.0
    container_name: newsletters-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: newsletters
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - "3307:3306"

  redis:
    image: redis:latest
    container_name: newsletters-redis
    ports:
      - "6380:6379"
