monitoring:
  security_alerts:
    # IP Reputation Monitoring
    ip_reputation:
      threshold: 50  # Risk score threshold
      action: block
      notification_channels:
        - email
        - slack

    # Rate Limiting Monitoring
    rate_limiting:
      global:
        window_ms: 900000  # 15 minutes
        max_requests: 100
        action: temporary_block
      
      auth:
        window_ms: 900000  # 15 minutes
        max_requests: 5
        action: permanent_block

    # CSRF Protection Monitoring
    csrf_protection:
      max_failures: 3
      block_duration: 3600  # 1 hour
      notification_threshold: 10

  logging:
    levels:
      security: info
      error: error
      audit: critical

    retention:
      security_logs: 90  # days
      error_logs: 180  # days
      audit_logs: 365  # days

  alerting:
    channels:
      email:
        - security@yourdomain.com
        - devops@yourdomain.com
      
      slack:
        webhook_url: ${SLACK_SECURITY_WEBHOOK}
      
      pagerduty:
        service_key: ${PAGERDUTY_SERVICE_KEY}

  periodic_checks:
    vulnerability_scan:
      frequency: weekly
      day: sunday
      time: "02:00"

    security_audit:
      frequency: monthly
      day: "first-monday"
      time: "03:00"

  performance_thresholds:
    response_time:
      warning: 500  # ms
      critical: 1000  # ms

    error_rate:
      warning: 5%  # Percentage of failed requests
      critical: 10%  # Percentage of failed requests

  intrusion_detection:
    suspicious_activities:
      - multiple_login_failures
      - unusual_ip_access
      - high_request_volume
      - potential_brute_force

    response_actions:
      block_ip: true
      require_2fa: true
      send_notification: true
