name: Weekly Dependency Check

on:
  schedule:
    # Run every Monday at 3 AM UTC
    - cron: '0 3 * * 1'

jobs:
  dependency-audit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Check Outdated Dependencies
      run: npm outdated
    
    - name: Dependency Vulnerability Scan
      run: npm audit --audit-level=high
    
    - name: Create GitHub Issue for Dependency Updates
      uses: actions/github-script@v7
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Dependency Updates Required',
            body: 'Automated dependency check detected outdated or vulnerable packages. Please review and update.'
          })
